# Версия схемы, которую мы используем.
version: '3'

#список сервисов
services:

  #сервис (даем любое угодное название)
  nginx:

    #образ контейнера
    image: nginx:latest

    #перечисляем директории, которые хотим пробросить в контейнер (система:контейнер)
    volumes:
      - ./:/var/www/ #все файлы из корня будут помещены в папку /var/www/ на сервере
      - ./nginx/conf.d/:/etc/nginx/conf.d/ #заменяем стандартный конфиг, на наш - кастомный

    ports:
      - "8888:80"

    container_name: app_nginx
