# Версия схемы, которую мы используем.
version: '3'

#список сервисов
services:

  #сервис (даем любое угодное название)
  nginx:

    #образ контейнера
    image: nginx:latest

    #перечисляем директории, которые хотим пробросить в контейнер (система:контейнер)
    volumes:
      - ./:/var/www/ #все файлы из корня будут помещены в папку /var/www/ на сервере
      - ./nginx/conf.d/:/etc/nginx/conf.d/ #заменяем стандартный конфиг, на наш - кастомный

    ports:
      - "8888:80"

    #контейнер nginx будет запущен, только при успешном старте контейнера php
    depends_on:
      - php
    container_name: app_nginx

  #сервис
  php:
    image: php:8.0-fpm
    volumes:
      - ./:/var/www/ #для пхп также выдаем доступ к файловой системе проекта
    container_name: app_php
